#!/bin/sh
# ==================================================================
# Kaname host helper.
#
#   kaname-host.sh caddyfile <data-dir>   write <data-dir>/Caddyfile
#   kaname-host.sh apply <data-dir>       run the queued host request
#
# The part of Kaname that has to run on the HOST rather than in a
# container, because everything it does ends in restarting the
# containers the control plane and the panel run in: a shell inside one
# of them would be killed by its own `docker compose up` and would never
# reach the health check below, let alone the rollback.
#
# `apply` is started by the path unit install.sh installs, when the
# control plane writes <data-dir>/updates/queue/request.json. The
# control plane has already done everything reversible before handing
# over — it snapshotted .env and wrote the new values into it. This
# script pulls, restarts, checks, and puts the snapshot back if the new
# build does not answer.
# ==================================================================
set -eu

LOCAL_API="http://127.0.0.1:4000"
HEALTH_TIMEOUT=120

# The control-plane image runs as this uid, fixed in its Dockerfile. The
# environment file is read *and rewritten* by it, so anything that puts
# that file back has to put its group and mode back too.
KANAME_UID=10001

CMD="${1:-}"
DATA_DIR="${2:-/etc/kaname}"
QUEUE="$DATA_DIR/updates/queue/request.json"
LOG_FILE=""

die() {
  echo "kaname-host: $*" >&2
  exit 1
}

say() {
  printf '%s %s\n' "$(date -u +%H:%M:%S)" "$*" | tee -a "$LOG_FILE"
}

compose() {
  docker compose -p "$PROJECT" -f "$DATA_DIR/docker-compose.yml" --env-file "$DATA_DIR/.env" "$@"
}

# One value out of the environment file. The last assignment wins, the
# same way Compose reads it.
env_value() {
  sed -n "s/^$1=//p" "$DATA_DIR/.env" | tail -n 1
}

# The control plane answers on the loopback interface whatever the panel
# is reachable as from outside, so this is the same check either way.
answering() {
  i=0
  while [ "$i" -lt "$HEALTH_TIMEOUT" ]; do
    if curl -fsS "$LOCAL_API/health" >>"$LOG_FILE" 2>&1; then
      return 0
    fi
    i=$((i + 1))
    sleep 1
  done
  return 1
}

# ------------------------------------------------------------------
# The Caddyfile
#
# Generated here and nowhere else: it is derived from the address in
# .env, and there is no copy of it anyone is meant to edit by hand.
#
# With no domain there is one site — plain HTTP on :80, at whatever
# address the box answers on. With a domain there are two, because the
# :80 site stays: setting a domain must never take away the URL the
# operator is looking at while DNS and the certificate catch up.
# ------------------------------------------------------------------
generate_caddyfile() {
  [ -f "$DATA_DIR/.env" ] || die "no environment file at $DATA_DIR/.env"

  domain="$(env_value KANAME_DOMAIN)"
  target="$DATA_DIR/Caddyfile"

  {
    cat <<'SHARED'
# ------------------------------------------------------------------
# Generated by kaname-host.sh from the address in .env. Every edit made
# here is lost the next time the panel's address changes.
#
# /api and /agent go to the control plane; everything else goes to the
# panel UI. Because both live under the same origin, the session cookie
# needs no CORS exemption.
# ------------------------------------------------------------------

(kaname) {
	encode zstd gzip

	# Agent sockets and API traffic.
	@control path /api/* /agent/* /health
	handle @control {
		reverse_proxy control-plane:4000 {
			# SSE and the terminal WebSocket must not be buffered.
			flush_interval -1
		}
	}

	# The agent installer, served from the control plane so the URL in
	# the enrollment command is the same host the agent will dial.
	handle /install.sh {
		reverse_proxy control-plane:4000
	}
	handle /download/* {
		reverse_proxy control-plane:4000
	}

	handle {
		reverse_proxy web:3000
	}

	header {
		X-Content-Type-Options nosniff
		Referrer-Policy strict-origin-when-cross-origin
		-Server
	}
}

# The address every install starts on, and keeps.
:80 {
	import kaname
}
SHARED

    if [ -n "$domain" ]; then
      cat <<SITE

$domain {
	import kaname

	# Only on the name Caddy holds a certificate for. Promising this on
	# the :80 site would break the IP the operator arrived by.
	header Strict-Transport-Security "max-age=31536000; includeSubDomains"
}
SITE
    fi
  } >"$target.partial"

  chmod 0644 "$target.partial"
  mv "$target.partial" "$target"
}

# ------------------------------------------------------------------
# Requests
#
# One field per line, quoted values only. The request is written by the
# control plane, not by a user, and holds nothing but identifiers.
# ------------------------------------------------------------------
field() {
  tr ',' '\n' <"$QUEUE" | grep "\"$1\"" | head -n 1 | cut -d'"' -f4
}

rollback() {
  say "!! $TO_VERSION did not come up"
  if [ -f "$SNAPSHOT_DIR/.env" ]; then
    say "--> restoring the configuration from $SNAPSHOT_DIR"
    cp "$SNAPSHOT_DIR/.env" "$DATA_DIR/.env"
    chmod 0660 "$DATA_DIR/.env"
    chown "root:$KANAME_UID" "$DATA_DIR/.env"
    if compose up -d --wait control-plane web >>"$LOG_FILE" 2>&1; then
      say "!! rolled back to $FROM_VERSION"
    else
      say "!! the rollback to $FROM_VERSION did not come up either — this needs a person"
    fi
  else
    say "!! no snapshot at $SNAPSHOT_DIR; leaving the deployment as it is"
  fi
  exit 1
}

do_update() {
  [ -n "$RUN_ID" ] || die "an update request with no run id"

  say "==> applying $TO_VERSION over $FROM_VERSION (run $RUN_ID)"

  # 1. Pull first. Nothing is stopped yet, so a pull that fails costs
  #    nothing but the time it took.
  say "--> pulling images"
  if ! compose pull control-plane web >>"$LOG_FILE" 2>&1; then
    say "!! could not pull the images for $TO_VERSION; nothing was stopped"
    rollback
  fi

  # 2. Restart. Compose waits for the health checks the project declares.
  say "--> restarting"
  if ! compose up -d --wait control-plane web >>"$LOG_FILE" 2>&1; then
    rollback
  fi

  # 3. Verify against the running control plane rather than trusting the
  #    container's own health check.
  say "--> waiting for the control plane to answer"
  if answering; then
    say ""
    say "==> $TO_VERSION is up and answering"
    exit 0
  fi

  say "!! no answer from $LOCAL_API/health after ${HEALTH_TIMEOUT}s"
  rollback
}

do_reconfigure() {
  say "==> applying the address in $DATA_DIR/.env"

  say "--> writing $DATA_DIR/Caddyfile"
  generate_caddyfile

  # Caddy for the site blocks, and the other two because the public URL
  # and the cookie policy are read once, at boot.
  say "--> recreating the proxy, the control plane and the panel"
  if ! compose up -d --force-recreate --wait caddy control-plane web >>"$LOG_FILE" 2>&1; then
    say "!! the deployment did not come back up; the previous address is gone from .env"
    exit 1
  fi

  say "--> waiting for the control plane to answer"
  if answering; then
    say ""
    say "==> the panel is answering on $(env_value KANAME_PUBLIC_URL)"
    exit 0
  fi

  say "!! no answer from $LOCAL_API/health after ${HEALTH_TIMEOUT}s"
  exit 1
}

apply() {
  [ -f "$QUEUE" ] || exit 0

  KIND="$(field kind)"
  RUN_ID="$(field run_id)"
  TO_VERSION="$(field to_version)"
  FROM_VERSION="$(field from_version)"
  PROJECT="$(field project)"
  SNAPSHOT_DIR="$(field snapshot_dir)"
  LOG_FILE="$(field log_file)"

  [ -n "$KIND" ] || { echo "kaname-host: unreadable request" >&2; rm -f "$QUEUE"; exit 1; }
  [ -n "$PROJECT" ] || PROJECT="kaname"
  [ -n "$LOG_FILE" ] || LOG_FILE="$DATA_DIR/updates/${RUN_ID:-host}.log"

  mkdir -p "$(dirname "$LOG_FILE")"
  : >"$LOG_FILE"
  chmod 0600 "$LOG_FILE"

  # The request is consumed immediately, so a crash below cannot leave a
  # path unit re-triggering this in a loop.
  rm -f "$QUEUE"

  case "$KIND" in
    update) do_update ;;
    reconfigure) do_reconfigure ;;
    *) say "!! nothing here knows how to do '$KIND'"; exit 1 ;;
  esac
}

case "$CMD" in
  caddyfile) generate_caddyfile ;;
  apply) apply ;;
  *) die "usage: kaname-host.sh caddyfile|apply <data-dir>" ;;
esac
